# an example docker compose.yml tweak environment file according to your deploy

version: '3'

services:
   odpreactor-server:
      build: .
      container_name: odpreactor-server
      ports:
        # Public HTTP Port:
        - "${ODPR_SERVER_PORT-6000}:${ODPR_SERVER_PORT-6000}"
      environment:
        - PORT=${ODPR_SERVER_PORT-6000}
        - HOST=${ODPR_SERVER_HOST-localhost}
        - ALLOWED_ORIGINS=${ODPR_SERVER_ALLOWED_ORIGINS-http://localhost:6001,http://localhost:6002}
        - CONFIG_SPARQL_ENDPOINT_URI=${CONFIG_SPARQL_ENDPOINT_URI-http://localhost/config/sparql}
        - CONFIG_GRAPH=${CONFIG_GRAPH-http://localhost/ld/config}
        - LOCAL=false
        - CI_TEST=false
        - TEST_ES_INDEX_URL=${TEST-ES-INDEX-URL-http://localhost:6999}
        - TEST_SPARQL_ENDPOINT_URI=${TEST_SPARQL_ENDPOINT_URI-http:localhost/config/sparql}
      env_file:
        - .env
      restart: always