# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: odp-reactor-server develop CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: ld-r build test
      run: npm install && npm run test && npm run build && npm run test 
      env:
        TEST_ES_INDEX_URL: http://localhost:9200
        TEST_SPARQL_ENDPOINT_URI: https://arco.istc.cnr.it/odpr/sparql
        CONFIG_SPARQL_ENDPOINT_URI: https://arco.istc.cnr.it/odpr/sparql
        CONFIG_GRAPH: http://odpreactor.arco.istc.cnr.it/configuration
        PORT: 4000
        ALLOWED_ORIGINS: http://localhost:3000,https://odp-reactor-ldr.herokuapp.com,https://odp-reactor-browser.vercel.app
        CI_TEST: true
        HOST: https://odp-reactor-server.herokuapp.com/